name: matta_harmonia
description: A period tracking app powered by Firebase
publish_to: "none" # Remove this if you plan to publish

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core
  firebase_core: ^2.27.0
  
  # (Add other Firebase packages as you expand, e.g. Firestore, Auth)
  # firebase_auth: ^4.17.8
  # cloud_firestore: ^4.16.0

  # Add other packages your app needs here

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
